/**
 * Fog of war — information visibility.
 *
 * Three levels per foreign army:
 *   HIDDEN  — not detected; no marker.
 *   CONTACT — inside a friendly unit's OUTER vision: position known, but not
 *             composition. Rendered as an unknown-contact marker ("?").
 *   VISIBLE — inside a friendly unit's INNER vision: full composition revealed.
 *
 * Vision is generated by friendly army stacks (per-unit outer/inner radii from
 * the unit catalogue, best unit in the stack wins). A foreign stack standing
 * on ground the viewer owns is also at least CONTACT — troops on your soil are
 * known to be there, even if their make-up is not. Own armies are always
 * VISIBLE. With fog disabled (sandbox / `fogOfWar === false`) everything is
 * VISIBLE.
 *
 * Owned province *centres* used to project a fixed 130-unit CONTACT ring, which
 * bled across borders and left enemy stacks sitting in their own land
 * permanently marked as an "unidentified force". That ring is gone: territory
 * vision is now exactly the territory.
 *
 * Pure and cheap: O(foreignArmies × visionSources). Recomputed on the sim
 * cadence, not per render frame. `player-view.ts` reuses `friendlyVisionSources`
 * / `pointContactLevel` to keep every fog decision on one implementation.
 */

import type { GameState } from './game-state';
import type { WorldData } from './world-data';
import { strongestGroup } from './units/army';
import { unitType } from './units/unit-catalog';
import { wrappedDistanceSq } from './geometry';

export type ContactLevel = 'hidden' | 'contact' | 'visible';

export interface VisionSource {
  x: number;
  z: number;
  outerSq: number;
  innerSq: number;
}

/** Moving eyes only: the viewer's own army stacks. Territory the viewer holds
 *  is handled separately (see `ownsGroundAt`) so it stays border-exact. */
export function friendlyVisionSources(
  state: GameState, _world: WorldData, viewerCountryId: number,
): VisionSource[] {
  const sources: VisionSource[] = [];
  for (const army of Object.values(state.armies)) {
    if (army.ownerCountryId !== viewerCountryId) continue;
    const lead = strongestGroup(army);
    const outer = lead ? unitType(lead.typeId).visionOuter : 150;
    const inner = lead ? unitType(lead.typeId).visionInner : 80;
    sources.push({ x: army.x, z: army.z, outerSq: outer * outer, innerSq: inner * inner });
  }
  return sources;
}

/** True when the world point sits inside a province the viewer owns. */
export function ownsGroundAt(
  state: GameState, world: WorldData, viewerCountryId: number, x: number, z: number,
): boolean {
  const provinceId = world.provinceAt(x, z);
  return provinceId >= 0 && state.provinceOwners[provinceId] === viewerCountryId;
}

/** Highest contact level a world point reaches against the given vision set. */
export function pointContactLevel(
  sources: readonly VisionSource[], x: number, z: number, worldWidth: number,
): ContactLevel {
  let level: ContactLevel = 'hidden';
  for (const source of sources) {
    const distSq = wrappedDistanceSq(source.x, source.z, x, z, worldWidth);
    if (distSq <= source.innerSq) return 'visible';
    if (distSq <= source.outerSq) level = 'contact';
  }
  return level;
}

export function computeArmyVisibility(
  state: GameState, world: WorldData, viewerCountryId: number,
): Map<string, ContactLevel> {
  const result = new Map<string, ContactLevel>();

  if (!state.fogOfWar) {
    for (const id of Object.keys(state.armies)) result.set(id, 'visible');
    return result;
  }

  const sources = friendlyVisionSources(state, world, viewerCountryId);
  for (const army of Object.values(state.armies)) {
    if (army.ownerCountryId === viewerCountryId) {
      result.set(army.id, 'visible');
      continue;
    }
    let level = pointContactLevel(sources, army.x, army.z, world.width);
    if (level === 'hidden' && ownsGroundAt(state, world, viewerCountryId, army.x, army.z)) {
      level = 'contact';
    }
    result.set(army.id, level);
  }
  return result;
}

/** True when the player may see any detail of `countryId`'s internal state
 *  (economy, production, buildings). Own country, or fog disabled. */
export function foreignDetailVisible(
  state: GameState, viewerCountryId: number, countryId: number,
): boolean {
  return countryId === viewerCountryId || !state.fogOfWar;
}
